#!/usr/bin/env python3
"""Generate paper-facing Future-Choice facts/tables from tracked artifacts."""
from __future__ import annotations

import argparse
from hashlib import sha256
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GEN = ROOT / "paper/generated"
CLAIM_MATRIX = ROOT / "results/transfer/future-choice-claim-matrix.json"
B_COMPONENT = ROOT / "results/transfer/asc-pull-query-component-strong-baselines.json"
B_SHARED = ROOT / "results/transfer/asc-pull-query-shared-opportunity-frontier.json"
B_DYNAMIC = ROOT / "results/transfer/asc-pull-query-dynamic-frontier-reuse.json"
C_N10 = ROOT / "results/transfer/uav-attention-n10-future-choice-summary.json"
C_SET = ROOT / "results/transfer/uav-attention-set-mst-attribution.json"
C_SCALE = ROOT / "results/transfer/uav-attention-n10-scale-statistics.json"
CLAIMS = ROOT / "results/CLAIMS.md"


def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def sha(path: Path) -> str:
    return sha256(path.read_bytes()).hexdigest()


def pct(x: float, n: int = 1) -> str:
    return f"{100.0 * float(x):.{n}f}"


def esc(s: str) -> str:
    return str(s).replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")


def render_facts() -> str:
    shared = load(B_SHARED)
    dyn = load(B_DYNAMIC)
    comp = load(B_COMPONENT)
    c10 = load(C_N10)
    cset = load(C_SET)
    cscale = load(C_SCALE)
    c16 = next(c for c in comp["cells"] if int(c["components"]) == 16)
    lines = [
        "% Generated by scripts/make_future_choice_artifacts.py; do not edit.",
        rf"\newcommand{{\FCSharedStaticUnionFalseNeg}}{{{shared['summary']['static_union_false_negative_cells']}/{shared['summary']['nontrivial_cells']}}}",
        rf"\newcommand{{\FCDynamicFreshBuildsMax}}{{{dyn['summary']['max_fresh_frontier_builds']}}}",
        rf"\newcommand{{\FCDynamicPersistentBuildsMax}}{{{dyn['summary']['max_persistent_frontier_builds']}}}",
        rf"\newcommand{{\FCComponentFreshExactC16}}{{{c16['totals']['fresh_exact_expanded']}}}",
        rf"\newcommand{{\FCComponentPersistentExactC16}}{{{c16['totals']['ordinary_persistent_exact_expanded']}}}",
        rf"\newcommand{{\FCComponentRecomputesC16}}{{{c16['totals']['incremental_conflict_component_recomputes']}}}",
        rf"\newcommand{{\FCComponentReusesC16}}{{{c16['totals']['incremental_conflict_component_reuses']}}}",
        rf"\newcommand{{\FCNtenCohortSize}}{{{len(c10['cohort'])}}}",
        rf"\newcommand{{\FCScaleCohortSize}}{{100}}",
        rf"\newcommand{{\FCPaperMatchedEpisodes}}{{50}}",
        rf"\newcommand{{\FCPaperMatchedConstructive}}{{{cscale['paper50']['constructive_hard_feasible_lower_bound_count']}}}",
    ]
    stems = {
        "nearest_neighbour": "NN",
        "nearest_deadline": "NDF",
        "greedy_deadline_battery": "GDB",
        "battery_aware_nn": "BANN",
    }
    for policy, row in cset["n10"]["rows"].items():
        q = row["n10_quality"]
        c = row["n10_compute"]
        stem = stems[policy]
        lines += [
            rf"\newcommand{{\FC{stem}DepthFourZero}}{{{q['depth4_zero_tardiness']}}}",
            rf"\newcommand{{\FC{stem}Zero}}{{{q['set_mst_lu_zero_tardiness']}}}",
            rf"\newcommand{{\FC{stem}FallbackPct}}{{{pct(c['set_mst_fallback_ratio_over_exact'])}\%}}",
            rf"\newcommand{{\FC{stem}TotalPct}}{{{pct(c['set_mst_total_ratio_over_exact'])}\%}}",
            rf"\newcommand{{\FC{stem}ReductionPct}}{{{pct(c['set_mst_total_reduction_vs_basic'])}\%}}",
        ]
    for policy, row in cscale["constructive100"].items():
        stem = stems[policy]
        methods = row["methods"]
        lines += [
            rf"\newcommand{{\FC{stem}ScaleNativeZero}}{{{methods['native']['zero_tardiness']['success']}}}",
            rf"\newcommand{{\FC{stem}ScaleDepthZero}}{{{methods['depth4']['zero_tardiness']['success']}}}",
            rf"\newcommand{{\FC{stem}ScaleFutureZero}}{{{methods['future_choice']['zero_tardiness']['success']}}}",
            rf"\newcommand{{\FC{stem}ScaleDepthComplete}}{{{methods['depth4']['completion']['success']}}}",
            rf"\newcommand{{\FC{stem}ScaleFutureComplete}}{{{methods['future_choice']['completion']['success']}}}",
            rf"\newcommand{{\FC{stem}ScaleDepthInfeasible}}{{{100-int(methods['depth4']['infeasible_free']['success'])}}}",
            rf"\newcommand{{\FC{stem}ScaleFutureInfeasible}}{{{100-int(methods['future_choice']['infeasible_free']['success'])}}}",
        ]
    return "\n".join(lines) + "\n"


def render_asc_table() -> str:
    shared = load(B_SHARED)
    dyn = load(B_DYNAMIC)
    comp = load(B_COMPONENT)
    c16 = next(c for c in comp["cells"] if int(c["components"]) == 16)
    rows = [
        ("Static union", f"{shared['summary']['static_union_false_negative_cells']}/{shared['summary']['nontrivial_cells']} false negatives", "representation failure"),
        ("Observation narrowing", f"{dyn['summary']['max_fresh_frontier_builds']} to {dyn['summary']['max_persistent_frontier_builds']} builds", "persistent domains"),
        ("Fresh ordered exact", str(c16["totals"]["fresh_exact_expanded"]), "exact expansions"),
        ("Persistent exact", str(c16["totals"]["ordinary_persistent_exact_expanded"]), "exact expansions"),
        ("Dependency-cache exact", str(c16["totals"]["dependency_cache_exact_expanded"]), f"separator replay={c16['totals']['dependency_separator_replay_success']}"),
        ("Conflict frontier", f"{c16['totals']['incremental_conflict_component_recomputes']} recompute / {c16['totals']['incremental_conflict_component_reuses']} reuse", "different work unit"),
    ]
    body = "\\\\\n".join(f"{esc(a)} & {esc(b)} & {esc(c)}" for a, b, c in rows)
    return "% Generated; do not edit.\n\\begin{tabular}{lll}\n\\toprule\nMechanism & Result & Unit / boundary\\\\\n\\midrule\n" + body + "\\\\\n\\bottomrule\n\\end{tabular}\n"


def render_uav_table() -> str:
    cset = load(C_SET)
    labels = {
        "nearest_neighbour": "Nearest neighbour",
        "nearest_deadline": "Nearest deadline",
        "greedy_deadline_battery": "Greedy deadline-battery",
        "battery_aware_nn": "Battery-aware NN",
    }
    rows = []
    for policy, label in labels.items():
        row = cset["n10"]["rows"][policy]
        q = row["n10_quality"]
        c = row["n10_compute"]
        rows.append((label, f"{q['depth4_zero_tardiness']}/21", f"{q['set_mst_lu_zero_tardiness']}/21", f"{pct(c['set_mst_fallback_ratio_over_exact'])}\\%", f"{pct(c['set_mst_total_ratio_over_exact'])}\\%", f"{pct(c['set_mst_total_reduction_vs_basic'])}\\%"))
    body = "\\\\\n".join(f"{esc(a)} & {b} & {c} & {d} & {e} & {f}" for a, b, c, d, e, f in rows)
    return "% Generated; do not edit.\n\\begin{tabular}{lrrrrr}\n\\toprule\nPolicy & Depth-4 zero-tardy & FutureChoice zero-tardy & Exact fallback & Total / exact & vs. basic U\\\\\n\\midrule\n" + body + "\\\\\n\\bottomrule\n\\end{tabular}\n"


def render_uav_scale_table() -> str:
    scale = load(C_SCALE)
    labels = {
        "nearest_neighbour": "Nearest neighbour",
        "nearest_deadline": "Nearest deadline",
        "greedy_deadline_battery": "Greedy deadline-battery",
        "battery_aware_nn": "Battery-aware NN",
    }
    rows = []
    for policy, label in labels.items():
        methods = scale["constructive100"][policy]["methods"]
        rows.append(
            (
                label,
                f"{methods['native']['zero_tardiness']['success']}/100",
                f"{methods['depth4']['zero_tardiness']['success']}/100",
                f"{methods['future_choice']['zero_tardiness']['success']}/100",
                f"{methods['depth4']['completion']['success']}/100",
                f"{methods['future_choice']['completion']['success']}/100",
                f"{100-int(methods['depth4']['infeasible_free']['success'])}",
                f"{100-int(methods['future_choice']['infeasible_free']['success'])}",
            )
        )
    body = "\\\\\n".join(
        f"{esc(a)} & {b} & {c} & {d} & {e} & {f} & {g} & {h}"
        for a, b, c, d, e, f, g, h in rows
    )
    return (
        "% Generated; do not edit.\n"
        "\\begin{tabular}{lrrrrrrr}\n\\toprule\n"
        "Policy & Native zero & Depth-4 zero & Future zero & Depth-4 comp. & Future comp. & Depth-4 infeas. & Future infeas.\\\\\n\\midrule\n"
        + body
        + "\\\\\n\\bottomrule\n\\end{tabular}\n"
    )


def outputs() -> dict[Path, str]:
    meta = {
        "stage": "FUTURE_CHOICE_PAPER_ARTIFACTS",
        "claim_authority": "results/CLAIMS.md F1-F7",
        "inputs": {str(p.relative_to(ROOT)): sha(p) for p in (CLAIM_MATRIX, B_COMPONENT, B_SHARED, B_DYNAMIC, C_N10, C_SET, C_SCALE, CLAIMS)},
        "boundaries": ["Search work is not wall time.", "N=15 seed1 is not a distribution result.", "C is external mission validation, not an emergency-communication benchmark."],
    }
    return {
        GEN / "future_choice_facts.tex": render_facts(),
        GEN / "table_future_choice_asc.tex": render_asc_table(),
        GEN / "table_future_choice_uav.tex": render_uav_table(),
        GEN / "table_future_choice_uav_scale.tex": render_uav_scale_table(),
        GEN / "future_choice_facts.meta.json": json.dumps(meta, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    GEN.mkdir(parents=True, exist_ok=True)
    drift = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                drift.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content, encoding="utf-8")
    if drift:
        raise SystemExit("Future-Choice generated artifact drift: " + ", ".join(drift))
    print("Future-Choice paper artifacts are current" if args.check else "Generated Future-Choice paper artifacts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
